### ISSUE TITLE
Login via QR code doesn't work

### ISSUE THREAD

**Issue by reckel-jm** [Craeckie/church-bot#1]
The login via QR Code does not work. See the picture below.

![Screenshot_2023-10-18-08-03-09-466_org.telegram.messenger~2.jpg](https://github.com/Craeckie/church-bot/assets/57252256/c7b7ca69-6b07-44c3-ae0c-c0d75fa4e164)

**Comment by Craeckie** [comment]
Fixed with ffbde04
